using Microsoft.EntityFrameworkCore;

namespace BallCom.Ordering.API.Data
{
    // Maakt schema idempotent aan (CREATE ... IF NOT EXISTS), zodat het ook werkt
    // op een bestaand Postgres-volume. Bewust GEEN EnsureCreated: die doet niets
    // zodra de database al bestaat en zou de nieuwe tabellen dan overslaan.
    public static class OrderingDbInitializer
    {
        public static async Task InitializeAsync(OrderingWriteDbContext context)
        {
            await context.Database.ExecuteSqlRawAsync("""
                -- Referentietabel met producten (vanuit Catalog via RabbitMQ).
                CREATE TABLE IF NOT EXISTS "Products" (
                    "Id"    uuid    PRIMARY KEY,
                    "Name"  text    NOT NULL DEFAULT '',
                    "Price" numeric NOT NULL DEFAULT 0
                );

                -- Order-id generator (id wordt op command-moment toegekend).
                CREATE SEQUENCE IF NOT EXISTS order_id_seq START 1;

                -- ============ SCHRIJFKANT (C): append-only event store ============
                CREATE TABLE IF NOT EXISTS "OrderEvents" (
                    "Sequence"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "StreamId"      text        NOT NULL,
                    "AggregateType" text        NOT NULL,
                    "Version"       integer     NOT NULL,
                    "EventType"     text        NOT NULL,
                    "Payload"       text        NOT NULL,
                    "OccurredAt"    timestamptz NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_OrderEvents_Stream_Version"
                    ON "OrderEvents" ("StreamId", "Version");

                -- ============ LEESKANT (Q): gedenormaliseerde read models ============
                CREATE TABLE IF NOT EXISTS "OrderSummaries" (
                    "OrderId"       integer     PRIMARY KEY,
                    "Status"        text        NOT NULL DEFAULT '',
                    "TotalPrice"    numeric     NOT NULL DEFAULT 0,
                    "CustomerEmail" text        NOT NULL DEFAULT '',
                    "CustomerName"  text        NOT NULL DEFAULT '',
                    "Street"        text        NOT NULL DEFAULT '',
                    "City"          text        NOT NULL DEFAULT '',
                    "PostalCode"    text        NOT NULL DEFAULT '',
                    "Country"       text        NOT NULL DEFAULT '',
                    "ItemCount"     integer     NOT NULL DEFAULT 0,
                    "PlacedAt"      timestamptz NOT NULL,
                    "LastUpdatedAt" timestamptz NOT NULL
                );

                CREATE TABLE IF NOT EXISTS "OrderLineViews" (
                    "Id"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "OrderId"   integer NOT NULL,
                    "ProductId" text    NOT NULL DEFAULT '',
                    "Quantity"  integer NOT NULL DEFAULT 0,
                    "Price"     numeric NOT NULL DEFAULT 0
                );

                CREATE TABLE IF NOT EXISTS "CustomerOrderStats" (
                    "CustomerEmail" text        PRIMARY KEY,
                    "OrderCount"    integer     NOT NULL DEFAULT 0,
                    "TotalSpent"    numeric     NOT NULL DEFAULT 0,
                    "LastOrderAt"   timestamptz NOT NULL
                );
                """);
        }
    }
}
